# logical opers

In [22]:
def logical_calc(array, op):
    if len(array) > 1:
        if op == "OR":
            curr = (array[0] | array[1])
            if len(array) > 2:
                for i in range(2, len(array)):
                    curr = curr | array[i]


        if op == "AND":
            curr = (array[0] & array[1])
            if len(array) > 2:
                for i in range(2, len(array)):
                    curr = curr & array[i]

        if op == "XOR":
            curr = (array[0] ^ array[1])
            if len(array) > 2:
                for i in range(2, len(array)):
                    curr = curr ^ array[i]
    else:
        return array[0]
    
    return curr
        
print(logical_calc([True, True, True, False, True, True], "XOR"))

True

# Task
Create a function that given a sequence of strings, groups the elements that can be obtained by rotating others, ignoring upper or lower cases.

In the event that an element appears more than once in the input sequence, only one of them will be taken into account for the result, discarding the rest.

Input
Sequence of strings. Valid characters for those strings are uppercase and lowercase characters from the alphabet and whitespaces.

Output
Sequence of elements. Each element is the group of inputs that can be obtained by rotating the strings.

Sort the elements of each group alphabetically.

Sort the groups descendingly by size and in the case of a tie, by the first element of the group alphabetically.

Examples
['Tokyo', 'London', 'Rome', 'Donlon', 'Kyoto', 'Paris', 'Okyot'] --> [['Kyoto', 'Okyot', 'Tokyo'], ['Donlon', 'London'], ['Paris'], ['Rome']]

['Rome', 'Rome', 'Rome', 'Donlon', 'London'] --> [['Donlon', 'London'], ['Rome']]

[] --> []

In [44]:
def group_cities(seq):
    result = []
    seq = list(set(seq))
    temp = []
    t1 = [] #tablica posortowanych duzych znakow
    print(seq)
    print()
    print()
    print()
    print()
    print()
    while seq != []:
        for city in seq:
            print(f"current city: {city}")
            t = ''.join(sorted(city.upper()))
            if temp == []:
                t1.append(t)
                temp.append(city)
                seq.remove(city)
            else:
                if t in t1:
                    t1.append(t)
                    temp.append(city)
                    seq.remove(city)
            #print(f"temp: {temp}")
            #print(f"t1: {t1}")
        
        #print("-"*90)
        #print(seq)
        #print("-"*90)
        #print("FINAL")
        #print("-"*90)
        #print(f"temp: {temp}")
        #print(f"t1: {t1}")
        #result.append(list(set(temp)))
        #print(f"res: {result}")
        #print("-"*90)
        #print()
        #print()
        #print()
        #print()
        
        temp = []
        t1 = []
    
    return sorted(result)

In [45]:
print(group_cities(['Tokyo', 'London', 'Rome', 'Donlon', 'Kyoto', 'Paris', 'Okyot']))
                                # should return [['Kyoto', 'Okyot', 'Tokyo'], ['Donlon', 'London'], ['Paris'], ['Rome']])

['Donlon', 'Paris', 'Okyot', 'London', 'Kyoto', 'Rome', 'Tokyo']





current city: Donlon
temp: ['Donlon']
t1: ['DLNNOO']
current city: Okyot
temp: ['Donlon']
t1: ['DLNNOO']
current city: London
temp: ['Donlon', 'London']
t1: ['DLNNOO', 'DLNNOO']
current city: Rome
temp: ['Donlon', 'London']
t1: ['DLNNOO', 'DLNNOO']
current city: Tokyo
temp: ['Donlon', 'London']
t1: ['DLNNOO', 'DLNNOO']
------------------------------------------------------------------------------------------
['Paris', 'Okyot', 'Kyoto', 'Rome', 'Tokyo']
------------------------------------------------------------------------------------------
FINAL
------------------------------------------------------------------------------------------
temp: ['Donlon', 'London']
t1: ['DLNNOO', 'DLNNOO']
res: [['Donlon', 'London']]
------------------------------------------------------------------------------------------




current city: Paris
temp: ['Paris']
t1: ['AIPRS']
current city: Kyoto
temp: ['Paris']
t1: ['AIPRS']
current city: Rome
temp: ['Paris']
t1: ['AIPRS']
current city: Tokyo
temp: ['Paris']
t1: ['AIPRS']
------------------------------------------------------------------------------------------
['Okyot', 'Kyoto', 'Rome', 'Tokyo']
------------------------------------------------------------------------------------------
FINAL
------------------------------------------------------------------------------------------
temp: ['Paris']
t1: ['AIPRS']
res: [['Donlon', 'London'], ['Paris']]
------------------------------------------------------------------------------------------




current city: Okyot
temp: ['Okyot']
t1: ['KOOTY']
current city: Rome
temp: ['Okyot']
t1: ['KOOTY']
current city: Tokyo
temp: ['Okyot', 'Tokyo']
t1: ['KOOTY', 'KOOTY']
------------------------------------------------------------------------------------------
['Kyoto', 'Rome']
------------------------------------------------------------------------------------------
FINAL
------------------------------------------------------------------------------------------
temp: ['Okyot', 'Tokyo']
t1: ['KOOTY', 'KOOTY']
res: [['Donlon', 'London'], ['Paris'], ['Okyot', 'Tokyo']]
------------------------------------------------------------------------------------------




current city: Kyoto
temp: ['Kyoto']
t1: ['KOOTY']
------------------------------------------------------------------------------------------
['Rome']
------------------------------------------------------------------------------------------
FINAL
------------------------------------------------------------------------------------------
temp: ['Kyoto']
t1: ['KOOTY']
res: [['Donlon', 'London'], ['Paris'], ['Okyot', 'Tokyo'], ['Kyoto']]
------------------------------------------------------------------------------------------




current city: Rome
temp: ['Rome']
t1: ['EMOR']
------------------------------------------------------------------------------------------
[]
------------------------------------------------------------------------------------------
FINAL
------------------------------------------------------------------------------------------
temp: ['Rome']
t1: ['EMOR']
res: [['Donlon', 'London'], ['Paris'], ['Okyot', 'Tokyo'], ['Kyoto'], ['Rome']]
------------------------------------------------------------------------------------------




[['Donlon', 'London'], ['Kyoto'], ['Okyot', 'Tokyo'], ['Paris'], ['Rome']]

In [39]:
city= 'Heheszki'
t = ''
t.join(sorted(city.upper()))

'EEHHIKSZ'